Merge Chatbot to Dev
StasNldva/NIX_java_education_Neledva_Stanislav_156 pull request #2
Opened 2021-10-12 17:15 UTC by StasNldva

ChatBot 2-st stage

ChatBot 3-rd stage

ChatBot 4-th stage

ChatBot 5-th stage

TASK ChatBot Completed!

2021-10-12 20:25 UTC, asrubel reviewed
Привет, папку out в гитигнор - не интересно смотреть на откомпиленные классы. Сделай еще один коммит и сожми в один. Пока апрува нет.

2021-10-14 10:04 UTC, StasNldva commented
Folder out/ added to .gitignore

2021-10-14 17:36 UTC, maxsomochkin requested changes
Удали из гита служебные файлы залей следующий коммит без них без

2021-10-14 17:46 UTC, maxsomochkin requested changes

2021-10-14 17:46 UTC, maxsomochkin commented on src/nix/education/java/chatbot/ChatBot.java
> +            else System.out.println("Try again.");
Лучше писать так, при большом объеме кода будет читабельнее:
if(answer == 2) {
System.out.println("You right!\nGoodbye, have a nice day!");
break;
   }         else{
 System.out.println("Try again.");
}
и для форматирования используй ctrl+alt+L

2021-10-18 18:39 UTC, StasNldva commented
Folder .idea deleted

2021-10-19 19:41 UTC, asrubel commented on git_start.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Этот файл также не нужен

2021-10-19 19:42 UTC, asrubel reviewed
то что находится в папке out также не нужно

2021-10-19 19:43 UTC, asrubel commented on src/nix/education/java/chatbot/ChatBot.java
> +        Scanner keyboard = new Scanner(System.in);
сканер можешь сделать один и загнать его в свойства - постоянно создавать не нужно кучу объектов

2021-10-20 16:32 UTC, StasNldva commented
Fixed code and added some files in .gitignore

2021-10-20 19:34 UTC, asrubel reviewed
Привет, код можно принять, но здесь есть мусор в виде файлов из out и файл git_start.iml

2021-10-21 12:39 UTC, asrubel approved these changes

2021-10-21 14:54 UTC, merged