Coffee Machine Project
StasNldva/NIX_java_education_Neledva_Stanislav_156 pull request #3
Opened 2021-11-19 11:09 UTC by Gramp2

Coffee Machine project is waiting for approve

2021-11-20 11:56 UTC, maxsomochkin requested changes
Перепиши программу

2021-11-20 11:56 UTC, maxsomochkin commented on src/nix/education/java/coffeemachine/CoffeeMachine.java
> +abstract class CoffeeMachine {
Абстрактные классы создаются, когда он обьединяет какие-то конкретные сущности общими свойствами и поведением. Например абстрактный класс Animal который обьединяет всех животных. А конкретными наследниками мы описываем специфических животных.
В твоем случае это интерфейс и правильнее назвать его как нибудь IngridietCalculator

2021-11-20 11:56 UTC, maxsomochkin commented on src/nix/education/java/coffeemachine/CoffeeMachine.java
> +class Calculate extends CoffeeMachine {
IngridietCalculatorImpl

2021-11-20 11:56 UTC, maxsomochkin commented on src/nix/education/java/coffeemachine/Main.java
> +public class Main extends Calculate {
Главный клас с точкой входа не должен являться наследником кастомных классов.

2021-11-20 11:56 UTC, maxsomochkin commented on src/nix/education/java/coffeemachine/Main.java
> +    private static void Display() {
Если уже погружаешься в ООП, зачем пользуешься статиками? Создай отдельный класс с методами и вызывай их из созданного обьекта в мейне

2021-11-20 11:56 UTC, maxsomochkin commented on src/nix/education/java/coffeemachine/Main.java
> +    private static void Check(Scanner scanner) {
Смысл в методы передавать стандартные джавовские классы?

2021-11-20 11:56 UTC, maxsomochkin commented on src/nix/education/java/coffeemachine/Main.java
> +        int N;
Названия давай более осмысленно

2021-11-20 11:56 UTC, maxsomochkin commented on src/nix/education/java/coffeemachine/TheRealCoffeeMachine.java
> +enum typeOfCoffee {
1. Название енамов как и классов enum TypeOfCoffee
2. Каждый класс и енам в отдельный файл
3. Все константы в енаме КАПСОМ

2021-11-20 11:56 UTC, maxsomochkin commented on src/nix/education/java/coffeemachine/TheRealCoffeeMachine.java
> +    protected int Water = 400;
Константы КАПСОМ

2021-11-20 11:56 UTC, maxsomochkin commented on src/nix/education/java/coffeemachine/TheRealCoffeeMachine.java
> +    protected void TAKE(int c) {
Название методов и переменных с маленькой буквы take.
Осмысленные названия переменных

2021-11-20 11:56 UTC, maxsomochkin commented on src/nix/education/java/coffeemachine/TheRealCoffeeMachine.java
> +        Water += fw;
Название методов и переменных с маленькой буквы water.
Осмысленные названия переменных

2021-11-20 11:56 UTC, maxsomochkin commented on src/nix/education/java/coffeemachine/TheRealCoffeeMachine.java
> +        while (true) {
Цикл в отдельный метод какого нибудь класса и вызвай его из уже созданного обьекта

2021-11-20 11:56 UTC, maxsomochkin commented on src/nix/education/java/coffeemachine/TheRealCoffeeMachine.java
> +            switch (action) {
Вложенные свичи это зло. Разбивай на методы

2021-11-20 11:56 UTC, maxsomochkin commented on src/nix/education/java/coffeemachine/TheRealCoffeeMachine.java
> +                case fill:
Логику под кейсом в отдельный метод

2021-11-23 15:38 UTC, Gramp2 commented on src/nix/education/java/coffeemachine/Main.java
> +    private static void Check(Scanner scanner) {
Так, Алексей говорил, что не нужно создавать все время новый сканнер, т.е самое логическое решение это передача в качестве параметра

2021-11-24 10:59 UTC, Gramp2 commented
Поправил заммечания

2021-12-05 17:18 UTC, asrubel commented on src/nix/education/java/coffeemachine/Main.java
> +    private static void Check(Scanner scanner) {
сделал бы его лучше свойством

2021-12-05 17:20 UTC, asrubel commented on src/nix/education/java/coffeemachine/Main.java
> +        screen.displayCalculation(scanner);
сканер можешь сделать финальным приватным свойством класса Screen

2021-12-05 17:20 UTC, asrubel commented on src/nix/education/java/coffeemachine/Screen.java
> +    protected void Display() {
методы все с маленькой буквы

2021-12-05 17:21 UTC, asrubel commented on src/nix/education/java/coffeemachine/Screen.java
> +    protected void Check(Scanner scanner) {
названия методов с маленькой буквы

2021-12-05 17:22 UTC, asrubel commented on src/nix/education/java/coffeemachine/StartResource.java
> +        WATER -= WATERFORESPRESSO;
ты здесь константы меняешь? наверное -  нет - WATER на самом деле это свойство хранящее в себе запасы воды? Ну тогда это не константа.

2021-12-05 17:22 UTC, asrubel commented on src/nix/education/java/coffeemachine/StartResource.java
> +    protected int WATER = 400;
это свойства а не константы

2021-12-05 17:23 UTC, asrubel commented on src/nix/education/java/coffeemachine/StartResource.java
> +    protected int WATERFORESPRESSO = 250;
константы можешь делать финальными

2021-12-05 17:25 UTC, asrubel commented on src/nix/education/java/coffeemachine/MakeCoffee.java
> +    protected void display(StartResource st) {
StartResource st - лучше сделать свойством, а так вообще ты зря создал еще один класс - проще ресурсы объединить со скрином (твои классы - это и будет класс описывающий кофе-машину).

2021-12-05 18:23 UTC, Gramp2 commented
Дело сделано

2021-12-05 18:44 UTC, asrubel approved these changes

2021-12-05 18:44 UTC, merged